# Generated by Django 4.0.1 on 2022-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('flag', models.CharField(blank=True, max_length=500)),
                ('coordinates', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CovidStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('confirmed', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('date', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('coordinates', models.CharField(blank=True, max_length=500)),
                ('country', models.ManyToManyField(to='app.Country')),
                ('statistics', models.ManyToManyField(to='app.CovidStatistics')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='statistics',
            field=models.ManyToManyField(to='app.CovidStatistics'),
        ),
    ]
