# Generated by Django 4.0.1 on 2022-01-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_country_options_alter_covidstatistics_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='states',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='states',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='states',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
