# Generated by Django 4.0.1 on 2022-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_country_latitude_alter_country_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='country',
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
